#pragma once

namespace ava
{
enum Result {
    E_OK,
    E_INVALID_ARGUMENT,
    E_NOT_IMPLEMENTED,

    // oodle
    E_OODLE_LIBRARY_MISSING,
    E_OODLE_FAILED_TO_LOAD,
    E_OODLE_BAD_SIGNATURE,

    // TAB
    E_TAB_INVALID_MAGIC,
    E_TAB_UNKNOWN_ENTRY,
    E_TAB_INPUT_REQUIRES_COMPRESSION_BLOCKS,
    E_TAB_COMPRESS_BLOCK_FAILED,
    E_TAB_DECOMPRESS_BLOCK_FAILED,

    // AAF
    E_AAF_INVALID_MAGIC,
    E_AAF_INVALID_CHUNK_MAGIC,
    E_AAF_COMPRESS_CHUNK_FAILED,
    E_AAF_DECOMPRESS_CHUNK_FAILED,

    // SARC
    E_SARC_INVALID_MAGIC,
    E_SARC_UNKNOWN_VERSION,

    // RBMDL
    E_RBMDL_INVALID_MAGIC,
    E_RBMDL_UNKNOWN_VERSION,
    E_RBMDL_BAD_CHECKSUM,

    // ADF
    E_ADF_INVALID_MAGIC,

    // AVTX
    E_AVTX_INVALID_MAGIC,
    E_AVTX_UNKNOWN_VERSION,
    E_AVTX_SOURCE_BUFFER_NEEDED,
};

#define AVA_FL_SUCCEEDED(x) (x == ava::Result::E_OK)
#define AVA_FL_FAILED(x) (x != ava::Result::E_OK)
}